# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMessageBox, QApplication, QWidget, QLabel
from PyQt5.QtGui import QIcon, QPixmap
from functions import *
from functools import partial
from math import *

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1181, 522)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMouseTracking(False)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("MDS-logo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setAutoFillBackground(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(90, 150, 261, 121))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.comboBox = QtWidgets.QComboBox(self.groupBox)
        self.comboBox.setGeometry(QtCore.QRect(50, 60, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.comboBox.setFont(font)
        self.comboBox.setMaxVisibleItems(12)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.currentIndexChanged.connect(self.on_combobox_changed, self.comboBox.currentIndex())
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(390, 150, 361, 211))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setObjectName("groupBox_2")
        self.pushButton_4 = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_4.setGeometry(QtCore.QRect(190, 60, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton.setGeometry(QtCore.QRect(50, 60, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.pushButton_3 = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_3.setGeometry(QtCore.QRect(190, 110, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_2 = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_2.setGeometry(QtCore.QRect(50, 110, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_5 = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_5.setGeometry(QtCore.QRect(50, 160, 261, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_5.setFont(font)
        self.pushButton_5.setObjectName("pushButton_5")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 30, 1091, 51))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(18)
        self.label.setFont(font)
        self.label.setTextFormat(QtCore.Qt.AutoText)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setWordWrap(False)
        self.label.setObjectName("label")
        # ------------------------------------ IMAGEM --------------------------
        self.label100 = QtWidgets.QLabel(self.centralwidget)
        self.label100.setGeometry(QtCore.QRect(150, 250, 321, 261))
        self.label100.setObjectName('label_100')
        self.pixmap100 = QPixmap('Earth-small.png')
        self.label100.setPixmap(self.pixmap100)

        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setGeometry(QtCore.QRect(790, 150, 311, 261))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.groupBox_3.setFont(font)
        self.groupBox_3.setObjectName("groupBox_3")
        self.pushButton_6 = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_6.setGeometry(QtCore.QRect(50, 160, 211, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_6.setFont(font)
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_7 = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_7.setGeometry(QtCore.QRect(50, 60, 211, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_7.setFont(font)
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_8 = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_8.setGeometry(QtCore.QRect(50, 210, 211, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_8.setFont(font)
        self.pushButton_8.setObjectName("pushButton_8")
        self.pushButton_9 = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_9.setGeometry(QtCore.QRect(50, 110, 211, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_9.setFont(font)
        self.pushButton_9.setObjectName("pushButton_9")
        self.groupBox_2.raise_()
        self.groupBox.raise_()
        self.label.raise_()
        self.groupBox_3.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 1181, 26))
        self.menuBar.setObjectName("menuBar")
        MainWindow.setMenuBar(self.menuBar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Mission Design Software"))
        self.groupBox.setTitle(_translate("MainWindow", "Central Body"))
        self.comboBox.setItemText(0, _translate("MainWindow", "Earth"))
        self.comboBox.setItemText(1, _translate("MainWindow", "Moon"))
        self.comboBox.setItemText(2, _translate("MainWindow", "Sun"))
        self.comboBox.setItemText(3, _translate("MainWindow", "Mercury"))
        self.comboBox.setItemText(4, _translate("MainWindow", "Venus"))
        self.comboBox.setItemText(5, _translate("MainWindow", "Mars"))
        self.comboBox.setItemText(6, _translate("MainWindow", "Jupiter"))
        self.comboBox.setItemText(7, _translate("MainWindow", "Saturn"))
        self.comboBox.setItemText(8, _translate("MainWindow", "Uranus"))
        self.comboBox.setItemText(9, _translate("MainWindow", "Neptune"))
        self.comboBox.setItemText(10, _translate("MainWindow", "Pluto"))
        self.comboBox.setItemText(11, _translate("MainWindow", "Other"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Orbit Definition"))
        self.pushButton_4.setText(_translate("MainWindow", "Hyperbolic"))
        self.pushButton.setText(_translate("MainWindow", "Circular"))
        self.pushButton_3.setText(_translate("MainWindow", "Parabolic"))
        self.pushButton_2.setText(_translate("MainWindow", "Elliptical"))
        self.pushButton_5.setText(_translate("MainWindow", "Type Unknown"))
        self.label.setText(_translate("MainWindow", "Mission Design Software"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Utilities"))
        self.pushButton_6.setText(_translate("MainWindow", "Julian Dates"))
        self.pushButton_7.setText(_translate("MainWindow", "Ephemeris"))
        self.pushButton_8.setText(_translate("MainWindow", "Propellant Mass"))
        self.pushButton_9.setText(_translate("MainWindow", "Plane Changes"))

    def on_combobox_changed(self):
        value = self.comboBox.currentIndex()
        self.label100.setGeometry(QtCore.QRect(150, 250, 321, 261))
        if value == 0:
            self.pixmap100 = QPixmap('Earth-small.png')
        elif value == 1:
            self.pixmap100 = QPixmap('Moon-small.png')
        elif value == 2:
            self.pixmap100 = QPixmap('Sun-small.png')
        elif value == 3:
            self.pixmap100 = QPixmap('Mercury-small.png')
        elif value == 4:
            self.pixmap100 = QPixmap('Venus-small.png')
        elif value == 5:
            self.pixmap100 = QPixmap('Mars-small.png')
        elif value == 6:
            self.pixmap100 = QPixmap('Jupiter-small.png')
        elif value == 7:
            self.pixmap100 = QPixmap('Saturn-small.png')
            self.label100.setGeometry(QtCore.QRect(62, 250, 321, 261))
        elif value == 8:
            self.pixmap100 = QPixmap('Uranus-small.png')
        elif value == 9:
            self.pixmap100 = QPixmap('Neptune-small.png')
        elif value == 10:
            self.pixmap100 = QPixmap('Pluto-small.png')
        elif value == 11:
            self.pixmap100 = QPixmap('MDS-logo-small.png')
        self.label100.setPixmap(self.pixmap100)

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())